0. Helllo.py
1. DataExplore.py
2. LogicOperation.py
2. FileProcess.py
3. DataPlot.py

## 0. Helllo

In [25]:
print("HelloWorld")

text="HelloWorld_Text"
print(text)

HelloWorld
HelloWorld_Text


### 1. DataExplore

### <font color='blue'> variables and reference</font>

In [26]:
# Data with operation 

height = 179.0
weight = 6870
bmi = weight / height ** 2
print(type(bmi))  # real numbers
print(id(weight))

<class 'float'>
2640784798160


In [27]:
w = weight 
print(w, 'id is ', id(w))

w = weight *0.3
print(w, 'id is ',id(w))

6870 id is  2640784798160
2061.0 id is  2640762852528


In [28]:
day_of_week = 5
 #-----------
x = "body mass index"
y = 'this works too'
z= x+y

In [29]:
# Boolean
F1 = True
F2 = False
F1+F2

1

In [30]:
### <font color='blue'>Array and Matrix Operation</font>

In [31]:
# Array and mtatrix
h1 = 1.73
h2 = 1.68
h3 = 1.71
h4 = 1.89
H1 = [h1, h2, h3, h4]
print(H1)

[1.73, 1.68, 1.71, 1.89]


In [32]:
### elements can be different in a list
### lists can be in a list

In [33]:
H2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
H2[0]
H2[0][0]

#--------- two dimensions

H3 = [["liz", 1.73],
        ["emma", 1.68],
        ["mom", 1.71],
        ["dad", 1.89]]

H3[0]
H3[0][0]
H3[0][0][0]
 
    # find elements
H2[-1] 
H2[-2]
H2[1:3]
H2[:4]
H2[5:]

[1.71, 'dad', 1.89]

In [34]:
# element cannot be changed in a tuple, try it!
T = ('a','b','c','d',1,2,3)
print(T)

T = () # reset the contains
print(T)

T = (1,)
print(T)

('a', 'b', 'c', 'd', 1, 2, 3)
()
(1,)


### <font color='blue'>Operation of Array</font>

In [35]:
H2[0:2] = ["lisa", 1.74]

 # 
del(H2[2])

tallest = max(H1)
shortest = min(H1)

In [36]:
# functions

round(16.68, 1) # 1 代表小數點右邊一位
round(16.68)  # 沒有第二個引數代表小數點右邊 0 位
help(round)
round(16.68,-1)  # -1 代表小數點左邊一位

H2.index("mom") # find the index 
H2.count(1.73) # count 
H2.count(1.71)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



1

### <font color='blue'>String Operation</font>

In [37]:
# String Operation
sister = "liz"
sister.capitalize()
sister.replace("z", "sa")

H2.append("me")
H2.append(1.79)

### <font color='blue'>import package: numpy</font>

In [48]:
import numpy
x=numpy.array([1, 2, 3])

import numpy as np
np.array([1, 2, 3])

from numpy import array
array([1, 2, 3])

W1 = [65.4, 59.2, 63.6, 88.4]
#W1 / H1 
c=np.divide(W1,H1)
print(c)

[37.80346821 35.23809524 37.19298246 46.77248677]


In [41]:
np_height = np.array(H1)
np_weight = np.array(W1)
bmi = np_weight / np_height ** 2

 #---- Different types: different behavior!
python_list = [1, 2, 3]
python_list + python_list

numpy_array = np.array([1, 2, 3])
numpy_array + numpy_array

 #---- Numpy Subsetting
bmi[1]
bmi > 21
bmi[bmi > 21]

array([21.85171573, 21.75028214, 24.7473475 ])

In [42]:
# 2D Numpy Arrays
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

np_2d.shape   # 2 rows, 5 columns
np_2d[0]
np_2d[1]
np_2d[:,1:3]
np_2d[0][2]
np_2d[0,2]

1.71

In [43]:
# In[7]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
np.mean(np_city[:,0])
np.median(np_city[:,0])
np.std(np_city[:,0])

0.19760222750768774

In [44]:
# Ranges 

In [46]:
np.arange(5) # np.arange(end): An array starting with 0 of increasing consecutive integers, stopping before end.
# 一個數組以0開始的連續整數增加，停止結束之前。

np.arange(3, 9) # np.a

#np.range(start, end): An array of consecutive increasing integers from start, stopping before end
# 從start，stoppin開始的連續遞增整數數組結束前

np.arange(3, 30, 5) 

array([ 3,  8, 13, 18, 23, 28])

### <font color='blue'> Dictionary Operation</font>

In [22]:
# In[]
D = {'Name':'Jivin', 'Age': 6};

dict1 = D.copy()
print(D, id(D))
print(dict1, id(dict1))

{'Name': 'Jivin', 'Age': 6} 2640762823616
{'Name': 'Jivin', 'Age': 6} 2640762837504


In [ ]:
r = b'ASCII string'